### ISSUE TITLE
app crashes at startup

### ISSUE THREAD

**Issue by Micha-Btz** [nioc/tumblr-photo-browse#3]
hey,
I want to give the app a try but it crashes after start up.

`I/ActivityManager( 2309): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=eu.nioc.tumblrbrowse/.activities.MainActivity (has extras)} from uid 10019 on display 0
V/WindowManager( 2309): addAppToken: AppWindowToken{35bd01a9 token=Token{1b07130 ActivityRecord{aab5e73 u0 eu.nioc.tumblrbrowse/.activities.MainActivity t12492}}} to stack=1 task=12492 at 0
V/WindowManager( 2309): Adding window Window{3de53648 u0 Starting eu.nioc.tumblrbrowse} at 12 of 18 (after Window{101e020 u0 org.telegram.messenger/org.telegram.ui.LaunchActivity})
I/ActivityManager( 2309): Start proc 15181:eu.nioc.tumblrbrowse/u0a168 for activity eu.nioc.tumblrbrowse/.activities.MainActivity
I/art     (15181): Late-enabling -Xcheck:jni
V/WindowManager( 2309): rotationForOrientationLw(orient=-1, last=0); user=0 
I/LoadedApk(15181): No resource references to update in package de.baumann.thema
I/LoadedApk(15181): No resource references to update in package de.baumann.thema
W/art     (15181): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/AndroidRuntime(15181): Shutting down VM
E/AndroidRuntime(15181): FATAL EXCEPTION: main
E/AndroidRuntime(15181): Process: eu.nioc.tumblrbrowse, PID: 15181
E/AndroidRuntime(15181): java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.nioc.tumblrbrowse/eu.nioc.tumblrbrowse.activities.MainActivity}: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/AndroidRuntime(15181): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
E/AndroidRuntime(15181): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
E/AndroidRuntime(15181): 	at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime(15181): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime(15181): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(15181): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(15181): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime(15181): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15181): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(15181): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(15181): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(15181): Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/AndroidRuntime(15181): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1269)
E/AndroidRuntime(15181): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1256)
E/AndroidRuntime(15181): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:329)
E/AndroidRuntime(15181): 	at eu.nioc.tumblrbrowse.TumblrBrowse.goToAccount(TumblrBrowse.java:46)
E/AndroidRuntime(15181): 	at eu.nioc.tumblrbrowse.activities.MainActivity.onCreate(MainActivity.java:61)
E/AndroidRuntime(15181): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime(15181): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(15181): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
E/AndroidRuntime(15181): 	... 10 more
W/ActivityManager( 2309):   Force finishing activity 1 eu.nioc.tumblrbrowse/.activities.MainActivity
I/OpenGLRenderer( 2309): Initialized EGL, version 1.4
W/ActivityManager( 2309): Activity pause timeout for ActivityRecord{aab5e73 u0 eu.nioc.tumblrbrowse/.activities.MainActivity t12492 f}
V/WindowManager( 2309): rotationForOrientationLw(orient=5, last=0); user=0 
I/Timeline(15729): Timeline: Activity_idle id: android.os.BinderProxy@2756fc4b time:191756235
I/Timeline( 2309): Timeline: Activity_windows_visible id: ActivityRecord{1bd32afa u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t12317} time:191756498
W/ResourceType( 5260): No package identifier when getting value for resource number 0x00000000
W/PackageManager( 5260): Failure retrieving resources for eu.nioc.tumblrbrowse: Resource ID #0x0
I/Process (15181): Sending signal. PID: 15181 SIG: 9

`
can you please take a look. 
TIA Micha

**Comment by nioc** [comment]
Hi.
Which android version are you using?

**Comment by Micha-Btz** [comment]
Sorry, I forget too add.
Android 5.1.1
Cyanogenmod cm-12.1

Am 25. März 2018 13:38:11 MESZ schrieb Nicolas <notifications@github.com>:
>Hi.
>Which android version are you using?

**Comment by nioc** [comment]
Ok, I checked with Android 5.1 (Lollipop) and reproduced your issue.
I'm sorry about it, but I won't try to fix it, because I use Android 7 (Nougat) and now 8 (Oreo) since the beginning of this project.
I will update the API min version (minSdkVersion) in the [app/build.gradle](https://github.com/nioc/tumblr-photo-browse/blob/master/app/build.gradle) to 24 (Nougat).
If you want to find the problem, let me know :smile:
